### ISSUE TITLE
How fast is it?

### ISSUE THREAD

**Issue by maximecb** [rougier/tiny-renderer#1]
Hi there! 

Very impressive (and cute) project. I get that this is an educational project and performance wasn't the goal, but I was wondering how fast your tiny renderer is? It would be good to include that information in the readme, and maybe a basic `benchmark.py` script.

I'm asking because I've been working on 3D environments for OpenAI Gym which use OpenGL, and OpenGL is often a pain to use when rendering headless. When running on a cluster or remotely, you need a virtual frame buffer. Different GPUs can have different capabilities, etc. If there was a way to extend this to write simple shaders in numpy, and have a stack of transformation matrices like OpenGL, it could be an interesting solution for those of us that need basic 3D graphics :)

**Comment by rougier** [comment]
I think it is very very slow (even though I tried to vectorize everything). But it can be useful when you only need a small rendering. Note that for headless GL you have also the [Mesa](https://mesa3d.org/intro.html) option.

Transformation matrices should be easy and for the shaders, I'm working on it, but it'll be probably even slower (note that the [original code](https://github.com/ssloy/tinyrenderer/wiki) has shaders).
